# Paths to ignore (partial matches)
ignore_paths:
  - ".build/"
  - "Pods/"
  - "fastlane/"
  - "Tests/"

# Files to ignore (exact matches)
ignore_files:
  - "Package.swift"
  - "Package.resolved"

# URLs to ignore (partial matches)
ignore_urls:
  - "example.com"
  - "localhost"
  - "127.0.0.1"